CREATE TABLE Mag 
(
	Cod_mag INT(3) PRIMARY KEY AUTO_INCREMENT,
	lien char(30) NOT NULL

);

CREATE TABLE Fourniseur
(
	Cod_four INT(4) PRIMARY KEY AUTO_INCREMENT,
	Nom CHAR(20) NOT NULL,
	Adresse CHAR(30) NOT NULL
);

CREATE TABLE F
(
	Id_F INT(3) PRIMARY KEY AUTO_INCREMENT,
	Cod_F char(1) NOT NULL
);

CREATE TABLE SF
(
	Id_SF INT(3) PRIMARY KEY AUTO_INCREMENT,
	Cod_SF CHAR(2) NOT NULL,
	Cod_F CHAR(1) NOT NULL,
	FOREIGN KEY (Cod_F) REFERENCES F(Cod_F)
);


